# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Khela Karo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Khela Karo
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'Khela KaroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Khela KaroUITests' do
    # Pods for testing
  end

end
